<?php

namespace ContainerBJxAC0Y;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCatTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\CatType' shared autowired service.
     *
     * @return \App\Form\CatType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\CatType'] = new \App\Form\CatType();
    }
}
