<?php

namespace ContainerBJxAC0Y;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDetailRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\DetailRepository' shared autowired service.
     *
     * @return \App\Repository\DetailRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\DetailRepository'] = new \App\Repository\DetailRepository(($container->services['doctrine'] ?? $container->load('getDoctrineService')));
    }
}
