<?php

namespace ContainerBJxAC0Y;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFormContactControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\FormContactController' shared autowired service.
     *
     * @return \App\Controller\FormContactController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\FormContactController'] = $instance = new \App\Controller\FormContactController(($container->privates['security.authentication_utils'] ?? $container->load('getSecurity_AuthenticationUtilsService')), ($container->privates['App\\Repository\\ContactRepository'] ?? $container->load('getContactRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.CshazM0'] ?? $container->load('get_ServiceLocator_CshazM0Service'))->withContext('App\\Controller\\FormContactController', $container));

        return $instance;
    }
}
