<?php

namespace ContainerUWI5Oxg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCatModifService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\CatModif' shared autowired service.
     *
     * @return \App\Form\CatModif
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/CatModif.php';

        return $container->privates['App\\Form\\CatModif'] = new \App\Form\CatModif();
    }
}
