<?php

namespace ContainerA9h3dIs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_5kysFxrService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5kysFxr' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5kysFxr'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'plat' => ['privates', '.errored..service_locator.5kysFxr.App\\Entity\\Plat', NULL, 'Cannot autowire service ".service_locator.5kysFxr": it needs an instance of "App\\Entity\\Plat" but this type has been excluded in "config/services.yaml".'],
        ], [
            'plat' => 'App\\Entity\\Plat',
        ]);
    }
}
