<?php

namespace ContainerOAAZRPx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UzX5OwoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.UzX5Owo' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.UzX5Owo'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'mi' => ['privates', 'mailer.mailer', 'getMailer_MailerService', true],
            'ms' => ['privates', 'App\\Service\\MailService', 'getMailServiceService', true],
        ], [
            'entityManager' => '?',
            'mi' => '?',
            'ms' => 'App\\Service\\MailService',
        ]);
    }
}
