<?php

namespace ContainerJYE5jz5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_0vGnDYVService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.0vGnDYV' shared service.
     *
     * @return \App\Service\MailerInterface
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\FormContactController::contactform()": the $mailer argument is type-hinted with the non-existent class or interface: "App\\Service\\MailerInterface".');
    }
}
