<?php

namespace ContainerQE9lfM2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPanierControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\PanierController' shared autowired service.
     *
     * @return \App\Controller\PanierController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/PanierController.php';
        include_once \dirname(__DIR__, 4).'/src/Service/PanierService.php';

        $a = ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack());
        $b = ($container->privates['App\\Repository\\PlatRepository'] ?? $container->load('getPlatRepositoryService'));

        $container->services['App\\Controller\\PanierController'] = $instance = new \App\Controller\PanierController($a, new \App\Service\PanierService($a, $b), $b);

        $instance->setContainer(($container->privates['.service_locator.CshazM0'] ?? $container->load('get_ServiceLocator_CshazM0Service'))->withContext('App\\Controller\\PanierController', $container));

        return $instance;
    }
}
