<?php

namespace ContainerW3dZhU4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Jg05LCService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._Jg05LC' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._Jg05LC'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'ms' => ['privates', 'App\\Service\\MailService', 'getMailServiceService', true],
        ], [
            'ms' => 'App\\Service\\MailService',
        ]);
    }
}
