<?php

namespace ContainerFZ6P7B3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_6ggdkZFService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6ggdkZF' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.6ggdkZF'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\AccueilController::cgu' => ['privates', '.service_locator.oogCZpI', 'get_ServiceLocator_OogCZpIService', true],
            'App\\Controller\\AccueilController::index' => ['privates', '.service_locator.2zw5m0y', 'get_ServiceLocator_2zw5m0yService', true],
            'App\\Controller\\AccueilController::login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\AccueilController::mlegal' => ['privates', '.service_locator.oogCZpI', 'get_ServiceLocator_OogCZpIService', true],
            'App\\Controller\\AccueilController::verifyUserEmail' => ['privates', '.service_locator.1Z9fEX7', 'get_ServiceLocator_1Z9fEX7Service', true],
            'App\\Controller\\CatController::cat' => ['privates', '.service_locator.oogCZpI', 'get_ServiceLocator_OogCZpIService', true],
            'App\\Controller\\CatController::contactform' => ['privates', '.service_locator.oogCZpI', 'get_ServiceLocator_OogCZpIService', true],
            'App\\Controller\\CatController::platcat' => ['privates', '.service_locator.oogCZpI', 'get_ServiceLocator_OogCZpIService', true],
            'App\\Controller\\CatController::platsearch' => ['privates', '.service_locator.oogCZpI', 'get_ServiceLocator_OogCZpIService', true],
            'App\\Controller\\FormContactController::contactform' => ['privates', '.service_locator.oogCZpI', 'get_ServiceLocator_OogCZpIService', true],
            'App\\Controller\\MailerController::sendEmail' => ['privates', '.service_locator.uVvF4gL', 'get_ServiceLocator_UVvF4gLService', true],
            'App\\Controller\\PlatController::cat' => ['privates', '.service_locator.oogCZpI', 'get_ServiceLocator_OogCZpIService', true],
            'App\\Controller\\PlatController::platform' => ['privates', '.service_locator.r1IfLNk', 'get_ServiceLocator_R1IfLNkService', true],
            'App\\Controller\\ProfilController::index' => ['privates', '.service_locator.t.5eM8v', 'get_ServiceLocator_T_5eM8vService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.oogCZpI', 'get_ServiceLocator_OogCZpIService', true],
            'App\\Controller\\RegistrationController::verifyUserEmail' => ['privates', '.service_locator.1Z9fEX7', 'get_ServiceLocator_1Z9fEX7Service', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\AccueilController:cgu' => ['privates', '.service_locator.oogCZpI', 'get_ServiceLocator_OogCZpIService', true],
            'App\\Controller\\AccueilController:index' => ['privates', '.service_locator.2zw5m0y', 'get_ServiceLocator_2zw5m0yService', true],
            'App\\Controller\\AccueilController:login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\AccueilController:mlegal' => ['privates', '.service_locator.oogCZpI', 'get_ServiceLocator_OogCZpIService', true],
            'App\\Controller\\AccueilController:verifyUserEmail' => ['privates', '.service_locator.1Z9fEX7', 'get_ServiceLocator_1Z9fEX7Service', true],
            'App\\Controller\\CatController:cat' => ['privates', '.service_locator.oogCZpI', 'get_ServiceLocator_OogCZpIService', true],
            'App\\Controller\\CatController:contactform' => ['privates', '.service_locator.oogCZpI', 'get_ServiceLocator_OogCZpIService', true],
            'App\\Controller\\CatController:platcat' => ['privates', '.service_locator.oogCZpI', 'get_ServiceLocator_OogCZpIService', true],
            'App\\Controller\\CatController:platsearch' => ['privates', '.service_locator.oogCZpI', 'get_ServiceLocator_OogCZpIService', true],
            'App\\Controller\\FormContactController:contactform' => ['privates', '.service_locator.oogCZpI', 'get_ServiceLocator_OogCZpIService', true],
            'App\\Controller\\MailerController:sendEmail' => ['privates', '.service_locator.uVvF4gL', 'get_ServiceLocator_UVvF4gLService', true],
            'App\\Controller\\PlatController:cat' => ['privates', '.service_locator.oogCZpI', 'get_ServiceLocator_OogCZpIService', true],
            'App\\Controller\\PlatController:platform' => ['privates', '.service_locator.r1IfLNk', 'get_ServiceLocator_R1IfLNkService', true],
            'App\\Controller\\ProfilController:index' => ['privates', '.service_locator.t.5eM8v', 'get_ServiceLocator_T_5eM8vService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.oogCZpI', 'get_ServiceLocator_OogCZpIService', true],
            'App\\Controller\\RegistrationController:verifyUserEmail' => ['privates', '.service_locator.1Z9fEX7', 'get_ServiceLocator_1Z9fEX7Service', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\AccueilController::cgu' => '?',
            'App\\Controller\\AccueilController::index' => '?',
            'App\\Controller\\AccueilController::login' => '?',
            'App\\Controller\\AccueilController::mlegal' => '?',
            'App\\Controller\\AccueilController::verifyUserEmail' => '?',
            'App\\Controller\\CatController::cat' => '?',
            'App\\Controller\\CatController::contactform' => '?',
            'App\\Controller\\CatController::platcat' => '?',
            'App\\Controller\\CatController::platsearch' => '?',
            'App\\Controller\\FormContactController::contactform' => '?',
            'App\\Controller\\MailerController::sendEmail' => '?',
            'App\\Controller\\PlatController::cat' => '?',
            'App\\Controller\\PlatController::platform' => '?',
            'App\\Controller\\ProfilController::index' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\RegistrationController::verifyUserEmail' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\AccueilController:cgu' => '?',
            'App\\Controller\\AccueilController:index' => '?',
            'App\\Controller\\AccueilController:login' => '?',
            'App\\Controller\\AccueilController:mlegal' => '?',
            'App\\Controller\\AccueilController:verifyUserEmail' => '?',
            'App\\Controller\\CatController:cat' => '?',
            'App\\Controller\\CatController:contactform' => '?',
            'App\\Controller\\CatController:platcat' => '?',
            'App\\Controller\\CatController:platsearch' => '?',
            'App\\Controller\\FormContactController:contactform' => '?',
            'App\\Controller\\MailerController:sendEmail' => '?',
            'App\\Controller\\PlatController:cat' => '?',
            'App\\Controller\\PlatController:platform' => '?',
            'App\\Controller\\ProfilController:index' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\RegistrationController:verifyUserEmail' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
