<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFx5CjaM\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFx5CjaM/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFx5CjaM.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFx5CjaM\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFx5CjaM\App_KernelDevDebugContainer([
    'container.build_hash' => 'Fx5CjaM',
    'container.build_id' => 'dc435ae0',
    'container.build_time' => 1686221640,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFx5CjaM');
