<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRpoUC0x\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRpoUC0x/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRpoUC0x.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRpoUC0x\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRpoUC0x\App_KernelDevDebugContainer([
    'container.build_hash' => 'RpoUC0x',
    'container.build_id' => '0673b316',
    'container.build_time' => 1688722790,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRpoUC0x');
