<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOAAZRPx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOAAZRPx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOAAZRPx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOAAZRPx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOAAZRPx\App_KernelDevDebugContainer([
    'container.build_hash' => 'OAAZRPx',
    'container.build_id' => '8840d328',
    'container.build_time' => 1711099784,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOAAZRPx');
