<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                '/build/runtime.js',
                '/build/vendors-node_modules_bootstrap_dist_js_bootstrap_esm_js-node_modules_jquery_dist_jquery_js.js',
                '/build/app.js',
            ],
        ],
        'app-react' => [
            'js' => [
                '/build/runtime.js',
                '/build/vendors-node_modules_core-js_modules_es_array_from_js-node_modules_core-js_modules_es_array_i-2d0dcd.js',
                '/build/app-react.js',
            ],
        ],
        'app-css' => [
            'js' => [
                '/build/runtime.js',
            ],
            'css' => [
                '/build/vendors-node_modules_bootstrap_dist_css_bootstrap_css.css',
                '/build/app-css.css',
            ],
        ],
    ],
],

]];
